spring:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token:
        expiration: 3600000 # 1시간(60분)
        header: Authorization
      refresh-token:
        expiration: 1209600000 # 2주
        header: Authorization-refresh