name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: SCP to EC2
        env:
          EC2_PEM: ${{ secrets.EC2_PEM }}
          EC2_USER: ec2-user
          EC2_HOST: ${{ secrets.EC2_HOST }}
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
          RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
        run: |
          echo "$EC2_PEM" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem ./build/libs/plantour.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/plantour.jar
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            sudo systemctl stop plantour
            sudo systemctl daemon-reload
            sudo systemctl start plantour
          EOF
