name: Ubuntu EC2 Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          scp -i private_key ./build/libs/plantour-*.jar $USER@$HOST:/path/to/deployment/plantour.jar
          ssh -i private_key $USER@$HOST << EOF
            sudo systemctl stop plantour || true
            sudo systemctl start plantour
          EOF
          rm -f private_key

      - name: Check deployment
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key $USER@$HOST "sudo systemctl is-active --quiet plantour && echo 'Plantour is running' || echo 'Plantour is not running'"
          rm -f private_key