name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy files via SCP
        env:
          EC2_PEM: ${{ secrets.EC2_PEM }}
        run: |
          echo "$EC2_PEM" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem ./build/libs/plantour.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

      - name: Deploy to EC2
        env:
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
          RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          BASE_URL: ${{ secrets.BASE_URL }}
          CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            export RDS_HOSTNAME=${RDS_HOSTNAME}
            export RDS_PORT=${RDS_PORT}
            export RDS_DB_NAME=${RDS_DB_NAME}
            export RDS_USERNAME=${RDS_USERNAME}
            export RDS_PASSWORD=${RDS_PASSWORD}
            export SECRET_KEY=${SECRET_KEY}
            export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            export GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
            export BASE_URL=${BASE_URL}
            export CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            sudo systemctl stop plantour
            sudo mv /home/${{ secrets.EC2_USER }}/plantour.jar /path/to/deployment/plantour.jar
            sudo systemctl start plantour
          EOF
