name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PEM }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ./build/libs/*.jar ${USER}@${HOST}:~/app.jar
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            pid=$(pgrep -f "java -jar app.jar" || echo "")
            if [ ! -z "$pid" ]; then
              kill $pid
            fi
            nohup java -jar ~/app.jar > ~/app.log 2>&1 &
          '
          rm -f private_key